services:
  django: &django
    build:
      context: .
      dockerfile: ${DOCKERFILE:-./compose/local/django/Dockerfile}
      args:
        BUILD_ENVIRONMENT: local
    image: scielo_tools_local_django
    container_name: scielo_tools_local_django
    depends_on:
      - redis
      - postgres
      - mailhog
      #- ollama
    volumes:
      - .:/app:z
      - ../packtools:/packtools:z
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    environment:
      SCMS_WEBAPP_VERSION: ${SCMS_WEBAPP_VERSION:-v0.0.3-qa}
    ports:
      - "8000:8000"
    command: /start

  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: scielo_tools_local_ollama
  #   runtime: nvidia
  #   gpus: all
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - NVIDIA_DRIVER_CAPABILITIES=compute,utility
  #   volumes:
  #     #- ollama_data:/root/.ollama
  #   ports:
  #     - "11434:11434"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: scielo_tools_local_mailhog
    ports:
      - "8029:8025"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: scielo_tools_local_postgres
    container_name: scielo_tools_local_postgres
    volumes:
      - ../scms_data/scielo_tools/data_dev:/var/lib/postgresql:Z
      - ../scms_data/scielo_tools/data_dev_backup:/backups:z
    ports:
      - "5439:5432"
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:8
    container_name: scielo_tools_local_redis
    ports:
      - "6399:6379"

  celeryworker:
    <<: *django
    image: scielo_tools_local_celeryworker
    container_name: scielo_tools_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
      #- ollama
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: scielo_tools_local_celerybeat
    container_name: scielo_tools_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
      #- ollama
    ports: []
    command: /start-celerybeat

volumes:
  ollama_data:
